config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, param: :_username
  post '/auth/login', to: 'authentication#login'
  delete '/auth/logout', to: 'authentication#logout'
  get '/auth/new', to: 'authentication#new_session'
  resources 'videos', only: %i(index create new) do
    member do
      put :like
      put :dislike
    end
  end
  root to: 'videos#index'
  get '/*a', to: 'application#not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
  validates :token, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :username, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password,
            length: { minimum: 6 },
            if: -> { new_record? || !password.nil? }

  has_many :videos, foreign_key: :created_by
  has_many :tokens
  has_many :votes
end

app/models/video.rb
class Video < ApplicationRecord
  validates :youtube_url, presence: true, uniqueness: false
  validate :validate_youtube_url
  belongs_to :user, foreign_key: :created_by
  has_many :votes
  before_save :format_url

  def like_by_user(user)
    user_id = user.is_a?(User) ? user.id : user
    votes.where(user_id: user_id).like.present?
  end

  def dislike_by_user(user)
    user_id = user.is_a?(User) ? user.id : user
    votes.where(user_id: user_id).dislike.present?
  end

  private
  def get_youtube_id_from_url
    if youtube_url.to_s.include? '?'
      youtube_url.to_s.split('?').last.match(/v=([A-Za-z0-9_]+)&?.*$/).try(:[],1)
    elsif youtube_url.to_s.match(/(www\.youtube\.com|youtu\.be)\/.+/)
      youtube_url.to_s.split('/').last
    end
  end

  def format_url
    self.youtube_url = "https://www.youtube.com/embed/#{get_youtube_id_from_url}"
  end

  def validate_youtube_url
    errors.add(:youtube_url, 'invalid_youtube_url') if get_youtube_id_from_url.blank?
  end


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :video
  scope :like, -> {where(like: true)}
  scope :dislike, -> {where(like: false)}
  validates :user_id, uniqueness: { scope: :video_id }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session

  def not_found
    render json: {error: 'not_found'}
  end

  def authorize_token
    header = request.headers['Authorization']
    header.to_s.split(' ').last || cookies['access-token']
  end

  def authorize_request
    token = authorize_token
    begin
      Token.find_by!(token: token)
      @decoded = JsonWebToken.decode(token)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      respond_to do |format|
        format.html { return redirect_to auth_new_path }
        format.any { render json: {error: 'not_found'}, status: :unauthorized }
      end
    rescue JWT::DecodeError => e
      respond_to do |format|
        format.html { return redirect_to auth_new_path }
        format.any { render json: {error: 'invalid_token', status: :unauthorized} }
      end
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def new_session
  end

  def login
    @current_user = User.find_by!(username: params[:username])
    if @current_user&.authenticate(params[:password])
      token = JsonWebToken.encode(user_id: @current_user.id)
      @current_user.tokens.create!(token: token)
      time = Time.now + 24.hours.to_i
      render json: {token: token, exp: time.strftime("%m-%d-%Y %H:%M"),
                    username: @current_user.username}, status: :ok
    else
      render json: {errors: 'Unauthorized'}, status: :unauthorized
    end
  rescue ActiveRecord::RecordNotFound
    render json: {errors: 'Invalid username or password'}, status: :unauthorized
  end

  def logout
    Token.find_by!(token: authorize_token).delete
    render json: {message: 'success'}, status: :ok
  end

  private

  def login_params
    params.permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_request, except: %i[new create]
  before_action :find_user, only: %i[show index]

  def index
    @users = User.all
    render json: @users, status: :ok
  end

  def show
    render json: @user, status: :ok
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to auth_new_path
    else
      render json: {errors: @user.errors.full_messages},
             status: :unprocessable_entity
    end
  end

  def update
    unless @user.update(user_params)
      render json: {errors: @user.errors.full_messages},
             status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
  end

  private

  def find_user
    @user = User.find_by!(username: params.require(:username))
  rescue ActiveRecord::RecordNotFound
    render json: {errors: 'User not found'}, status: :not_found
  end

  def user_params
    params.require(:user).permit(
        :username, :password, :password_confirmation
    )
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authorize_request, except: :index
  before_action :find_video, only: %i[like dislike]
  before_action :remove_all_votes, only: %i[like dislike]

  def index
    @current_user = Token.find_by(token: authorize_token)&.user if authorize_token
    @videos = Video.all.order(:created_at)
  end

  def like
    vote = Vote.create(video: @video, user: @current_user)
    render json: {success: true, data: vote}
  end

  def dislike
    vote = @current_user.votes.create(video: @video, like: false, user: @current_user)
    render json: {success: true, data: vote}
  end

  def create
    video = Video.create!(video_params.merge(created_by: @current_user.id))
    render json: {success: true, data: video}
  end

  private

  def video_params
    params.permit(:youtube_url, :desc, :title)
  end

  def remove_all_votes
    @current_user.votes.where(video_id: params[:id]).delete_all
  end

  def find_video
    @video = Video.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/authentication/new_session.html.erb
<h1> Log in</h1>

<form class="new_user" id="new_user" action="/auth/login" accept-charset="UTF-8" method="post"><input type="hidden">
  <div class="field">
    <label for="username">Username</label><br>
    <input autofocus="autofocus" autocomplete="username" type="email" name="username" id="username" class="form-control">
  </div>

  <div class="field">
    <label for="password">Password</label><br>
    <input autocomplete="off" type="password" name="password" id="password" class="form-control">
  </div>
  <button type="button" name="commit" value="Log in" class="btn btn-success form-control my-2" id="login">Log in
  </button>
  <%= link_to('Register', new_user_path, class: "form-control btn btn-info") %>
</form>

<script type="text/javascript" charset="utf-8">
    $("#login").on('click', () => {
        $.ajax({
            url: "/auth/login",
            method: "post",
            data: {
                username: $("#username").val(),
                password: $("#password").val()
            }
        }).done(function (response) {
            Cookies.set("access-token", response.token);
            window.location.replace('/videos')
        }).fail(function (error) {
            let message = JSON.parse (error.responseText).errors
            Swal.fire({
                type: 'error',
                title: message,
                showConfirmButton: false,
                timer: 1000
            })
        })

    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunnyMovie</title>
  <%= csrf_meta_tags %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="/"> <i class="fa fa-play"></i> Funny movie</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
      <%- if @current_user.present? %>
        <div class="ml-auto">Welcome <b><%= @current_user.username %></b></div>
        <form class="form-inline my-2 my-lg-0 ">
          <button class="btn btn-primary my-2 mx-1 my-sm-0" data-toggle="modal" data-target="#insertVideoModal" type="button">Share
            video
          </button>
          <button class="btn btn-danger my-2 mx-1 my-sm-0" data-toggle="modal" id="logout" type="button">Log out
          </button>
        </form>
      <%- else %>
        <%= link_to("Log in ", auth_new_path, class: "btn btn-primary my-2 mx-1 my-sm-0 ml-auto") %>
      <%- end %>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="insertVideoModal" tabindex="-1" role="dialog" aria-labelledby="insertVideoLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="insertVideoLabel">Insert youtube video</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render "videos/form" %>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <div class="mt-4">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, html: {id: "new_user_form"}) do |f| %>
  <div class="field form-group">
    <%= f.label :username %><br/>
    <%= f.email_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :password %><br/>
    <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
  </div>


  <div class="field form-group">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="actions">
    <button type="button" name="commit" class="btn btn-primary" id="register" data-disable-with="Register">
      Register
    </button>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">

    $("#register").on('click', () => {
        $.ajax({
            url: "/users",
            method: "post",
            data: $('#new_user_form').serializeArray()
        }).done(function (response) {
            Swal.fire({
                type: 'success',
                title: 'successfully',
                onClose: () => {
                  location.replace("/auth/new")
                }
            })

        }).fail(function (error) {
            let messages = JSON.parse (error.responseText).errors
            Swal.fire({
                type: 'error',
                title: messages[0],
                showConfirmButton: false,
                timer: 1000
            })
        })
    })
</script>

app/views/users/new.html.erb
<h2>Register</h2>
<%= render 'users/form' %>

app/views/videos/_form.html.erb
<form>

  <div class="form-group">
    <input type="text" class="form-control" id="youtubeTitle" placeholder="Title">
  </div>

  <div class="form-group">
    <input type="text" class="form-control" id="youtubeDesc" placeholder="Description">
  </div>

  <div class="form-group">
    <input type="url" class="form-control" id="youtubeUrl" placeholder="Insert Youtube URL">
  </div>
  <button type="button" class="btn btn-primary" id="shareYoutubeUrl">Share</button>
</form>

<script type="text/javascript" charset="utf-8">
    $("#shareYoutubeUrl").on("click", () => {
        $.ajax({
            headers: {
                'Authorization': `Bearer ${Cookies.get('access-token')}`
            },
            url: "/videos.json",
            method: "post",
            data: {
                youtube_url: $("#youtubeUrl").val(),
                title: $("#youtubeTitle").val(),
                desc: $("#youtubeDesc").val(),
            }
        }).done(function (response) {
            $('#insertVideoModal').modal('hide');
            Swal.fire({
                type: 'success',
                title: 'successfully',
                showConfirmButton: false,
                timer: 500
            })
            location.reload(true)

        }).fail(function () {
            Swal.fire({
                type: 'error',
                title: 'unexpected error',
                showConfirmButton: false,
                timer: 500
            })
        })
    })

</script>

app/views/videos/_show.html.erb
<div class="row mt-1">
  <div class="col-sm-3">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="<%= video.youtube_url %>?rel=0" allowfullscreen></iframe>
    </div>
  </div>
  <div class="col-sm-5" data=<%= video.id %>>
    <h3>
      <%= video.title || 'Missing title' %>
      <%- if @current_user %>
        <span>
          <%- if video.like_by_user(@current_user) %>
            <i class="clickable fa fa-thumbs-up" aria-hidden="true"></i>
          <%- elsif video.dislike_by_user(@current_user) %>
            <i class="clickable fa fa-thumbs-down" aria-hidden="true"></i>
          <%- else %>
            <i class="clickable fa fa-thumbs-o-up" aria-hidden="true"></i>
            <i class="clickable fa fa-thumbs-o-down" aria-hidden="true"></i>
          <%- end %>
        </span>
      <%- end %>
    </h3>
    <h4> shared by <%= video.user.username %></h4>
    <p>
      <span>
        <i class="fa fa-thumbs-o-up" aria-hidden="true"> <%= video.votes.like.size %></i>
        <i class="fa fa-thumbs-o-down" aria-hidden="true"><%= video.votes.dislike.size %></i>
      </span>
    </p>
    <p> <%= video.desc || 'Missing description' %></p>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container-fluid mt-3">
  <%- @videos.each do |video| %>
    <%= render 'videos/show', video: video %>
  <% end %>
</div>


<script type="text/javascript" charset="utf-8">
    document.addEventListener("turbolinks:load", function() {
        const notify_success = () => {
            Swal.fire({
                type: 'success',
                title: 'successfully',
                showConfirmButton: false,
                timer: 500
            })
        }

        const notify_error = () => {
            Swal.fire({
                type: 'error',
                title: 'unexpected error',
                showConfirmButton: false,
                timer: 500
            })
        }


        function like(video_id) {
            $.ajax({
                url: `/videos/${video_id}/like`,
                method: "put",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader ("Authorization", `Basic ${Cookies.get('access-token')}` )
                }
            }).done(function (response) {
                notify_success()
                location.reload(true)
            }).fail(function () {
                notify_error()
            })
        }

        function dislike(video_id) {
            $.ajax({
                url: `/videos/${video_id}/dislike`,
                method: "put",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader ("Authorization", `Basic ${Cookies.get('access-token')}` )
                }
            }).done(function (response) {
                notify_success()
                location.reload(true)
            }).fail(function () {
                notify_error()
            })
        }

        let likeable = event => {
            $this = $(event.target)
            $this.removeClass("fa-thumbs-o-up")
            $this.removeClass("fa-thumbs-down")
            $this.addClass("fa-thumbs-up")
            $this.siblings().remove()
            $this.unbind('click', likeable)
            $this.bind('click', dislikeable)
            let video_id = $this.parent().closest('div').attr('data')
            like(video_id)
        }

        let dislikeable = event => {
            $this = $(event.target)
            $this.removeClass("fa-thumbs-o-down")
            $this.removeClass("fa-thumbs-up")
            $this.addClass("fa-thumbs-down")
            $this.siblings().remove()
            $this.unbind('click', dislikeable)
            $this.bind('click', likeable)
            let video_id = $this.parent().closest('div').attr('data')
            dislike(video_id)
        }

        $("i.clickable.fa-thumbs-o-up").on('click', likeable)
        $("i.clickable.fa-thumbs-o-down").on('click',dislikeable)
        $("i.clickable.fa-thumbs-up").on('click',dislikeable)
        $("i.clickable.fa-thumbs-down").on('click', likeable)

        $("#logout").on('click', () => {
            $.ajax({
                url: `/auth/logout`,
                method: "delete",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader ("Authorization", `Basic ${Cookies.get('access-token')}` )
                }
            }).done(function (response) {
                notify_success()
                Cookies.remove('access-token')
                location.reload(true)
            }).fail(function () {
                notify_error()
            })
        })
    })


</script>